name = "aiken-lang/marlowe"
version = "0.0.0"
license = "Apache-2.0"
description = "Marlowe validator implemented in Aiken"

[repository]
user = "aiken-lang"
project = "marlowe"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "main"
source = "github"
