#!/usr/bin/env bash

# Always execute from within the parent folder.
cd $(dirname -- "${BASH_SOURCE[0]}")/..

aiken build --uplc

aiken blueprint apply --validator "marlowe.execute" --out plutus.json  "581c$(cat plutus.json | jq -r '.validators[1].hash')"

aiken blueprint convert --validator "marlowe.role_payout" > artifacts/marlowe.role_payout.plutus

aiken blueprint convert --validator "marlowe.execute" > artifacts/marlowe.execute.plutus
